### PR TITLE
Add React Native 0.25+ compatibility with imports

### PR DESCRIPTION
**Pull request by juankiz**

### CODE REVIEW

**Comment by juankiz** [comment]
@ide @brentvatne do you guys have some comments?

**Comment by danscan** [comment]
This looks good @juankiz.  Was about to do it myself and then saw this.  Can someone please merge? (CC @brentvatne)

**Comment by danscan** [comment]
I am using this PR's branch in my project w/ `react-native@0.26.2`.  Can confirm it works.

Just needs a major version bump before publishing.

**Comment by ide** [comment]
Published as 0.4.0.

**Comment by danscan** [comment]
Nice. Thanks @ide!

**Comment by juankiz** [comment]
Tanks @ide 👍

**Pull request merged**
